var xBoardDimensionSize = 8;
var yBoardDimensionSize = 8;
var oneSquareSize = 86;
var xCanvasSize = xBoardDimensionSize * oneSquareSize;
var yCanvasSize = yBoardDimensionSize * oneSquareSize;
var xBoardStartPos = 0;
var yBoardStartPos = 0;
var lineSquareSize = 2;
var initBoardWithWhiteSquare = true;